### ISSUE TITLE
不支持armeabi架构

### ISSUE THREAD

**Issue by Doonkey** [TencentCloud/tencentcloud-sdk-android-soe#4]
发现提供的依赖并没有支持armeabi架构，就这样放弃治疗了吗？能兼容一下吗？

**Comment by gregzeng11** [comment]
注意：NDK 以前支持 ARMv5 (armeabi) 以及 32 位和 64 位 MIPS，但 NDK r17 已不再支持。

https://developer.android.com/ndk/guides/abis?hl=zh-cn
